import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Locale;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class EditProfile extends JFrame {
    private JPanel panel;
    private JTextField firstName;
    private JTextField lastName;
    private JTextField email;
    private JPasswordField password;
    private JPasswordField confirmpassword;
    private JButton registerButton;
    private JTextField Pin;

    public EditProfile() {
        super("ABBank Edit Profile");
        ImageIcon backgroundImage = new ImageIcon(Objects.requireNonNull(getImage("edit_background.png")));
        this.setContentPane(new JLabel(backgroundImage));
        this.setLayout(new GridBagLayout());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setSize(995, 588);
        this.setLocationRelativeTo(null);
        panel.setOpaque(false);
        this.add(panel);
        this.setResizable(false);
        this.setVisible(true);
        APIHandle apiHandle = APIHandle.getInstance();
        apiHandle.refreshInformation();
        firstName.setEnabled(false);
        lastName.setEnabled(false);
        firstName.setText(apiHandle.getFirstName());
        lastName.setText(apiHandle.getLastName());
        email.setText(apiHandle.getEmail());
        JOptionPane.showMessageDialog(null, "Edit only the fields you wish to change", "Edit your profile", JOptionPane.INFORMATION_MESSAGE);
        registerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                String mail = email.getText();
                String pwd = String.valueOf(password.getPassword());
                String PIN = String.valueOf(Pin.getText());
                String cpwd = String.valueOf(confirmpassword.getPassword());
                if (!validateEMail(mail) && !mail.equals(""))
                    JOptionPane.showMessageDialog(null, "Please enter a valid e-mail address!", "ERROR", JOptionPane.ERROR_MESSAGE);
                else if (!pwd.equals(cpwd) && !pwd.equals(""))
                    JOptionPane.showMessageDialog(null, "Confirm password does not match password!", "ERROR", JOptionPane.ERROR_MESSAGE);
                else if (!validatePIN(PIN) && !PIN.equals(""))
                    JOptionPane.showMessageDialog(null, "The PIN you have entered is invalid! (ONLY 4 DIGITS)", "ERROR", JOptionPane.ERROR_MESSAGE);
                else {
                    APIHandle apiHandle = APIHandle.getInstance();
                    if (apiHandle.editProfile(PIN, mail, pwd)) {
                        JOptionPane.showMessageDialog(null, "Successfully edited your profile!", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                        changeVis(false);
                    }
                }

            }
        });
    }

    public void changeVis(boolean to) {
        this.setVisible(to);
    }

    private boolean validateEMail(String mail) {
        String regex = "^(.+)@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(mail);
        if (matcher.matches()) {
            return true;
        } else {
            return false;
        }
    }

    private boolean validatePIN(String PIN) {
        Pattern pattern = Pattern.compile("^[0-9]{4}$");
        Matcher matcher = pattern.matcher(PIN);
        boolean matchFound = matcher.find();
        return matchFound;
    }

    private Image getImage(String filename) {
        try {
            return ImageIO.read(Objects.requireNonNull(getClass().getResourceAsStream(
                    "/" + filename)));
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel1.add(panel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        firstName = new JTextField();
        firstName.setBackground(new Color(-5131595));
        firstName.setColumns(16);
        Font firstNameFont = this.$$$getFont$$$(null, Font.BOLD, 14, firstName.getFont());
        if (firstNameFont != null) firstName.setFont(firstNameFont);
        firstName.setForeground(new Color(-16777216));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(34, 500, 0, 0);
        panel.add(firstName, gbc);
        lastName = new JTextField();
        lastName.setBackground(new Color(-5131595));
        lastName.setColumns(16);
        Font lastNameFont = this.$$$getFont$$$(null, Font.BOLD, 14, lastName.getFont());
        if (lastNameFont != null) lastName.setFont(lastNameFont);
        lastName.setForeground(new Color(-16777216));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(34, 500, 0, 0);
        panel.add(lastName, gbc);
        email = new JTextField();
        email.setBackground(new Color(-5131595));
        email.setColumns(16);
        Font emailFont = this.$$$getFont$$$(null, Font.BOLD, 14, email.getFont());
        if (emailFont != null) email.setFont(emailFont);
        email.setForeground(new Color(-16777216));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(34, 500, 0, 0);
        panel.add(email, gbc);
        password = new JPasswordField();
        password.setBackground(new Color(-5131595));
        password.setColumns(16);
        Font passwordFont = this.$$$getFont$$$(null, Font.BOLD, 14, password.getFont());
        if (passwordFont != null) password.setFont(passwordFont);
        password.setForeground(new Color(-16777216));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(34, 500, 0, 0);
        panel.add(password, gbc);
        confirmpassword = new JPasswordField();
        confirmpassword.setBackground(new Color(-5131595));
        confirmpassword.setColumns(16);
        Font confirmpasswordFont = this.$$$getFont$$$(null, Font.BOLD, 14, confirmpassword.getFont());
        if (confirmpasswordFont != null) confirmpassword.setFont(confirmpasswordFont);
        confirmpassword.setForeground(new Color(-16777216));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(34, 500, 0, 0);
        panel.add(confirmpassword, gbc);
        registerButton = new JButton();
        registerButton.setBackground(new Color(-3933677));
        registerButton.setText("Save Changes");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 10;
        gbc.insets = new Insets(24, 500, 0, 0);
        panel.add(registerButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.insets = new Insets(70, 0, 0, 0);
        panel.add(spacer1, gbc);
        Pin = new JTextField();
        Pin.setBackground(new Color(-5131595));
        Pin.setColumns(16);
        Font PinFont = this.$$$getFont$$$(null, Font.BOLD, 14, Pin.getFont());
        if (PinFont != null) Pin.setFont(PinFont);
        Pin.setForeground(new Color(-16777216));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(34, 500, 0, 0);
        panel.add(Pin, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

}
